base_url = "https://arnab-half-blood-prince.github.io"
title = "Arnab Chakraborty"
description = "Arnab Chakraborty is a radio astronomer and observational cosmologist working on 21 cm intensity mapping, large-scale structure, and radio-interferometric data analysis."
default_language = "en"
compile_sass = false
build_search_index = false
generate_feed = false

[markdown]
highlight_code = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = true

[extra]
role = "Dunlap Fellow"
affiliation = "Dunlap Institute for Astronomy and Astrophysics, University of Toronto"
location = "Toronto, Canada"
email = "arnab.chakraborty@dunlap.utoronto.ca"
github = "https://github.com/Arnab-half-blood-prince"
linkedin = "https://www.linkedin.com/in/arnab-chak/"
orcid = "https://orcid.org/0000-0002-7758-9859"
ads = "https://ui.adsabs.harvard.edu/search/q=docs(library%2F0M0G3dsjSNeXotLDUmsR6Q)&sort=date%20desc%2C%20bibcode%20desc&p_=0"

menu_items = [
  { path = "/Research/", name = "Research" },
  { path = "/Publications/", name = "Publications" },
  { path = "/Softwares/", name = "Software" },
  { path = "/Resources/", name = "Resources" },
  { path = "/Talks/", name = "Talks" },
  { path = "/CV/", name = "CV" },
]
